#!/usr/bin/env node

const net = require('net')
const { render, handle_input, handle_message, send_message } = require('./lib/helpers')
const conn = net.createConnection('./bank.sock')



function connection_ready() {
	render([
		'Hello Customer'
	])
	send_message(conn, 'customer', 'customer')
}



function connection_closed() {
	console.log('connection closed')
}



handle_input(line => {
	// console.log(`Prompt command entered:`, line)
	send_message(conn, line, 'customer')
})



handle_message(conn, packet => {

	console.log('Message received:', packet.message)
})










conn.on('ready', connection_ready)

conn.on('close', () => {
	connection_closed()
	process.exit(1)
})

conn.on('error', () => {
	console.log('No connection')
	process.exit(1)
})