#!/usr/bin/env node

const net = require('net')
const { render, handle_input, handle_message, send_message } = require('./lib/helpers')
const conn = net.createConnection('./bank.sock')



function connection_ready() {
	render([
		'Hello Teller'
	])
	send_message(conn, 'connected', 'teller')
}



handle_input(line => {
	send_message(conn, line, 'teller')
})



handle_message(conn, packet => {
	// console.log(packet.type)
	console.log(packet.message)
})



conn.on('ready', connection_ready)

conn.on('close', () => {
	console.log('connection closed')
	process.exit(1)
})

conn.on('error', () => {
	console.log('No connection')
	process.exit(1)
})